server:
  port: 8080
  servlet:
    context-path: /jpay # Sau này API sẽ là http://localhost:8080/jpay/users

spring:
  application:
    name: Jpay Core Banking

#  datasource:
#    # Kết nối vào cổng 3307
#    url: jdbc:mysql://localhost:3307/jpay_db
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    # Nếu không có biến môi trường (chạy IntelliJ), dùng localhost:3307
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/jpay_db?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Hiện SQL
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
jwt:
  signerKey: "54321678901234567890123456789012"
  valid-duration: 3600
  refreshable-duration: 2592000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

